// Code generated by "enumer -type=Mode -text"; DO NOT EDIT.

package flags

import (
	"fmt"
	"strings"
)

const _ModeName = "ClientNexusServer"

var _ModeIndex = [...]uint8{0, 6, 11, 17}

const _ModeLowerName = "clientnexusserver"

func (i Mode) String() string {
	if i >= Mode(len(_ModeIndex)-1) {
		return fmt.Sprintf("Mode(%d)", i)
	}
	return _ModeName[_ModeIndex[i]:_ModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ModeNoOp() {
	var x [1]struct{}
	_ = x[Client-(0)]
	_ = x[Nexus-(1)]
	_ = x[Server-(2)]
}

var _ModeValues = []Mode{Client, Nexus, Server}

var _ModeNameToValueMap = map[string]Mode{
	_ModeName[0:6]:        Client,
	_ModeLowerName[0:6]:   Client,
	_ModeName[6:11]:       Nexus,
	_ModeLowerName[6:11]:  Nexus,
	_ModeName[11:17]:      Server,
	_ModeLowerName[11:17]: Server,
}

var _ModeNames = []string{
	_ModeName[0:6],
	_ModeName[6:11],
	_ModeName[11:17],
}

// ModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ModeString(s string) (Mode, error) {
	if val, ok := _ModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Mode values", s)
}

// ModeValues returns all values of the enum
func ModeValues() []Mode {
	return _ModeValues
}

// ModeStrings returns a slice of all String values of the enum
func ModeStrings() []string {
	strs := make([]string, len(_ModeNames))
	copy(strs, _ModeNames)
	return strs
}

// IsAMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Mode) IsAMode() bool {
	for _, v := range _ModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Mode
func (i Mode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Mode
func (i *Mode) UnmarshalText(text []byte) error {
	var err error
	*i, err = ModeString(string(text))
	return err
}
