#!/bin/bash
#
# Run the tester agains racket-langserver so magic-racket configuration is simpler.

go run tester/main.go -logFile=/tmp/racket/lsp.log -fileFormat=keyword -logLevel=debug -command="racket --lib racket-langserver" "$@"
